### ISSUE TITLE
Question about Belfast

### ISSUE THREAD

**Issue by chris48s** [openregister/local-authority-data#39]
In the [Northern Ireland register](https://github.com/openregister/local-authority-data/blob/master/data/local-authority-nir/local-authorities.tsv) I would expect that either there would be be a row `NIR-Z`, `Belfast`, `Belfast City Council`, `2015-03-31` in the file or the start date for `BFS` would be earlier than `2015-04-01` (or at least blank, like the other 'old' NI council records).

1) Is this a mistake and `NIR-Z` should exist?
2. Is this because `BFS` describes an organisation (Belfast City Council) which has had more than one administrative boundary associated with it (i.e: both https://mapit.mysociety.org/area/145955.html and https://mapit.mysociety.org/area/14333.html are both boundaries which have been associated with the organisation described by the id `BFS`) but all the other 2015 NI boundary changes actually created new/different administrative organisations?

If its the first one, can I submit a PR to add `NIR-Z`?

If it is the second one, presumably this means the start date on https://github.com/openregister/local-authority-data/blob/master/data/local-authority-nir/local-authorities.tsv#L34 is incorrect as it implies that `BFS` came into existence on `2015-04-01`?

**Comment by nacnudus** [comment]
Thanks @chris48s, that is a good question.  I will put it to the custodian.

Out of interest, which of the two options do you prefer?  Ultimately it's the custodian's call, but it's useful to us to understand how people interpret the information in registers so that we can create better documentation.

**Comment by chris48s** [comment]
> it's useful to us to understand how people interpret the information in registers

Hi @nacnudus  - allow me to answer that with a giant wall of text ;)

First of all, I guess it depends on the intended relationship between your IDs and boundary changes/organisational changes. I'm making some assumptions here - please correct me if I'm wrong, but presumably the point of inventing a new coding scheme for local authorities (instead of just calling them `N09000003`, or whatever) is that you are assigning an identifier to an _administrative body_ rather than a _boundary_. Then you can maintain a stable ID across boundary iterations which describe the same _organisation_ (which in principle may have N geographic boundaries associated with it at various points in time) - right?

So lets, for a moment, look at some different (clearer) examples:

If we take the identifier `STV` (Stevenage), in 2013 it had a minor boundary change - it used to be [E07000101](https://mapit.mysociety.org/area/144310.html) and now it is [E07000243](https://mapit.mysociety.org/area/2347.html). The ONS coding system is about describing a _boundary_ - so when this change happens, the area gets a new ID because `E07000101` describes a different geographic area to `E07000243` but this minor boundary tweak hasn't meaningfully changed Stevenage Borough Council - its still fundamentally the same organisation, so you still call it `STV` (right?). If you change that identifier every time the boundary changes then a) your nice human-readable codes won't stay human-readable for very long and b) your codes just duplicate another id schema which already exists. Hopefully that is all right?

Conversely, lets consider at a situation where 2 district councils merge into a new unitary authority (say Mid Bedfordshire and South Bedfordshire merging to become Central Bedfordshire in 2009). If something like that happens in future, it isn't just a trivial boundary change that has happened - the actual nature of the organisation(s) the identifiers describe has changed so presumably in that case you would retire the old IDs and create an ID to describe the describe the new body which has been legislated into existance. Again, hopefully that is correct?

So, under those assumptions, lets move back to Northern Ireland:

> which of the two options do you prefer?

I guess it depends on whether the legislation that changed the boundaries changed the _organisation_ or just changing the _boundary_ - i.e: If Belfast City Council pre-2015 and post-2015 is fundamentally the same organisation but covering a different geographical area then it should maintain a stable identifier across that boundary change. If Belfast City Council pre-2015 and post-2015 are 2 meaningfully different organisations, then they should have 2 different ids (assuming all of the above assumptions ar right). Either way, I think the current register content implies that up until `2015-03-31`, there was no Belfast City Council and that should be corrected one way or the other.

In terms of reading the actual details of the legislation (which I haven't done) and defining the term "meaningful", I'll leave that to the custodian but I guess fundamentally my ask would be: pick a rule, apply it consistently moving forward and document clearly what the rule is.

**Comment by nacnudus** [comment]
Thanks!  This is really useful.

You're absolutely right that we separate the concepts of 'boundary' and 'administrative body', and this register is about the administrative body.  Whether or not Belfast City Council is the same pre-2015 and post-2015 is the question I'll put to the custodian, but the keys used (at least to begin with) will be from the [ISO 3166-2:GB](https://en.wikipedia.org/wiki/ISO_3166-2:GB) standard, which didn't change the code for Belfast in 2015.  So we'll probably do something more like your second option.

Having said that, something we haven't decided yet is whether to include historic changes in the register, so when the final version is made ready to use, it might only have the most recent versions.

**Comment by nacnudus** [comment]
This was resolved in ed4bee5025e400fd3b59629a180cf83c25c1b98b.  The custodian chose not to give Belfast a start-date.
