### ISSUE TITLE
Inconsistent short-form/long-form naming

### ISSUE THREAD

**Issue by chris48s** [openregister/local-authority-data#45]
Is there any reason why some areas use the "City of ..." prefix in their short-form names and some don't?

For example:

* "Bristol City Council" / "City of Bristol": https://github.com/openregister/local-authority-data/blob/master/data/local-authority-eng/local-authorities.tsv#L13
* "City of Lincoln Council" / "City of Lincoln": https://github.com/openregister/local-authority-data/blob/master/data/local-authority-eng/local-authorities.tsv#L257

.. but conversely:

* "City of York Council" / "York": https://github.com/openregister/local-authority-data/blob/master/data/local-authority-eng/local-authorities.tsv#L94
* "City of Bradford Metropolitan District Council" / "Bradford": https://github.com/openregister/local-authority-data/blob/master/data/local-authority-eng/local-authorities.tsv#L12
* "City of Wolverhampton Council" / "Wolverhampton": https://github.com/openregister/local-authority-data/blob/master/data/local-authority-eng/local-authorities.tsv#L89
* "City of Westminster" / "Westminster": https://github.com/openregister/local-authority-data/blob/master/data/local-authority-eng/local-authorities.tsv#L189

(I understand that "City of London" is a special case in this respect)

**Comment by nacnudus** [comment]
For the `name` field, the custodian chose to use the names chosen by the local authorities themselves, as explained in a [blog post](https://data.blog.gov.uk/2016/10/26/meet-the-custodian-of-the-beta-local-authority-england-register/).

> Local authority names are important in terms of local identity and civic pride. Because the value of registers is derived from accurately recording and maintaining information on the world as it exists, there is nothing to be gained by mandating the varying styles authorities choose to write their names.

The values in the `official-name` field were the most common form that appeared in legislation when the register was created.

**Comment by chris48s** [comment]
Thanks for the response. I'll to close this issue given the question is answered and this condition occurs by design.
