### ISSUE TITLE
Shepway Council is now called Folkestone & Hythe

### ISSUE THREAD

**Issue by chris48s** [openregister/local-authority-data#47]
https://www.folkestone-hythe.gov.uk/news/change-of-name-approved

**Comment by Jamie-Atkinson** [comment]
Hi Chris

Thank you for getting in touch. this was updated within the register on the 5th of April
https://local-authority-eng.register.gov.uk/records/SHE

Once a register is ready to use we do not maintain the data held on GitHub.

all the best

Jamie

**Comment by chris48s** [comment]
cheers :+1:
