### ISSUE TITLE
'website' field points to 301 some cases

### ISSUE THREAD

**Issue by symroe** [openregister/local-authority-data#9]
There are 18 places where the website points to a 301. 

Normally this is because the register contains a link to the `http` version rather than the `https` version. 

Sometimes the domain name is wrong, e.g http://www.suffolkcoastal.gov.uk -> http://www.eastsuffolk.gov.uk

| Status Code | Register URL | Redirect URL |
| --- | --- | --- |
| 301 | http://richmondshire.gov.uk | http://www.richmondshire.gov.uk/ |
| 301 | http://www.broadland.gov.uk | https://www.broadland.gov.uk/ |
| 301 | http://www.mendip.gov.uk | http://www.mendip.gov.uk/resident |
| 301 | http://www.newcastle-staffs.gov.uk | https://www.newcastle-staffs.gov.uk/ |
| 301 | http://www.norfolk.gov.uk | https://www.norfolk.gov.uk/ |
| 301 | http://www.northnorfolk.org | http://www.north-norfolk.gov.uk/ |
| 301 | http://www.northwarks.gov.uk | https://www.northwarks.gov.uk/ |
| 301 | http://www.norwich.gov.uk | https://www.norwich.gov.uk/ |
| 301 | http://www.nuneatonandbedworth.gov.uk | https://www.nuneatonandbedworth.gov.uk/ |
| 301 | http://www.oxfordshire.gov.uk | https://www.oxfordshire.gov.uk/ |
| 301 | http://www.scarborough.gov.uk | https://www.scarborough.gov.uk/ |
| 301 | http://www.sstaffs.gov.uk | https://www.sstaffs.gov.uk/ |
| 301 | http://www.staffordshire.gov.uk | https://www.staffordshire.gov.uk/ |
| 301 | http://www.suffolk.gov.uk | https://www.suffolk.gov.uk/ |
| 301 | http://www.suffolkcoastal.gov.uk | http://www.eastsuffolk.gov.uk |
| 301 | http://www.surreycc.gov.uk | https://www.surreycc.gov.uk/ |
| 301 | http://www.waveney.gov.uk | http://www.eastsuffolk.gov.uk |
| 301 | http://www.west-norfolk.gov.uk | https://www.west-norfolk.gov.uk/ |

**Comment by symroe** [comment]
Of course I can submit a PR to change the above, but we might want to think about checking the status code of a URL at the point it's added to the register, so as to catch some of these things.

**Comment by symroe** [comment]
Also, `lincoln.gov.uk` and `rugby.gov.uk` both redirect from `http` to `https` using a `302`. I'm not sure what to do about this, as the status code implies that it's not permanent.

**Comment by symroe** [comment]
`http://cherwell-dc.gov.uk` uses a `302` to redirect to `http://www.cherwell.gov.uk`, however I expect it's meant to be a `301`.

**Comment by psd** [comment]
Thanks Sym! Talking to our custodian we're starting to think the website is the responsibility of the Open central government websites list, which could become a separate register.

**Comment by symroe** [comment]
"Fixed" by removing the field
